const libros = [
  {
    nombre: "Cien años de soledad",
    autor: "Gabriel García Márquez",
    genero: "Realismo mágico",
    tema: "Historia familiar",
    isbn: "978-3-16-148410-0",
    ejemplares: 10,
    disponibles: 5,
    descripcion: {
      paginas: 471,
      editorial: "Editorial Sudamericana",
      fechaPublicacion: "1967",
      resumen: "La historia de la familia Buendía en el pueblo ficticio de Macondo.",
    },
  },
  {
    nombre: "El amor en los tiempos del cólera",
    autor: "Gabriel García Márquez",
    genero: "Romance",
    tema: "Amor",
    isbn: "978-0-14-012389-0",
    ejemplares: 8,
    disponibles: 3,
    descripcion: {
      paginas: 348,
      editorial: "Editorial Oveja Negra",
      fechaPublicacion: "1985",
      resumen: "Una historia de amor entre Fermina Daza y Florentino Ariza que se extiende por más de cincuenta años.",
    },
  },
  {
    nombre: "La vorágine",
    autor: "José Eustasio Rivera",
    genero: "Novela",
    tema: "Selva amazónica",
    isbn: "978-84-376-0494-7",
    ejemplares: 12,
    disponibles: 7,
    descripcion: {
      paginas: 470,
      editorial: "Editorial Cromos",
      fechaPublicacion: "1924",
      resumen: "La historia de Arturo Cova y su aventura en la selva amazónica colombiana.",
    },
  },
  {
    nombre: "Delirio",
    autor: "Laura Restrepo",
    genero: "Thriller",
    tema: "Locura",
    isbn: "978-0-307-27946-5",
    ejemplares: 15,
    disponibles: 10,
    descripcion: {
      paginas: 416,
      editorial: "Alfaguara",
      fechaPublicacion: "2004",
      resumen: "La historia de Agustina y su lucha contra la locura en la Bogotá contemporánea.",
    },
  },
  {
    nombre: "La tejedora de coronas",
    autor: "Germán Espinosa",
    genero: "Histórica",
    tema: "Siglo XVIII",
    isbn: "978-958-30-0500-8",
    ejemplares: 9,
    disponibles: 4,
    descripcion: {
      paginas: 671,
      editorial: "Planeta",
      fechaPublicacion: "1982",
      resumen: "La vida de Genoveva Alcocer en la Cartagena de Indias del siglo XVIII.",
    },
  },
  {
    nombre: "El olvido que seremos",
    autor: "Héctor Abad Faciolince",
    genero: "Biografía",
    tema: "Violencia",
    isbn: "978-84-339-7589-0",
    ejemplares: 14,
    disponibles: 9,
    descripcion: {
      paginas: 274,
      editorial: "Alfaguara",
      fechaPublicacion: "2006",
      resumen: "Un relato autobiográfico sobre la vida y muerte del padre del autor.",
    },
  },
  {
    nombre: "Rosario Tijeras",
    autor: "Jorge Franco",
    genero: "Thriller",
    tema: "Violencia urbana",
    isbn: "978-84-204-6714-5",
    ejemplares: 11,
    disponibles: 6,
    descripcion: {
      paginas: 207,
      editorial: "Alfaguara",
      fechaPublicacion: "1999",
      resumen: "La historia de Rosario Tijeras, una mujer sicaria en Medellín.",
    },
  },
  {
    nombre: "María",
    autor: "Jorge Isaacs",
    genero: "Romance",
    tema: "Amor",
    isbn: "978-84-935356-5-3",
    ejemplares: 7,
    disponibles: 2,
    descripcion: {
      paginas: 324,
      editorial: "Editorial Norma",
      fechaPublicacion: "1867",
      resumen: "La historia de amor entre María y Efraín en el Valle del Cauca.",
    },
  },
  {
    nombre: "El coronel no tiene quien le escriba",
    autor: "Gabriel García Márquez",
    genero: "Realismo mágico",
    tema: "Soledad",
    isbn: "978-84-96548-65-4",
    ejemplares: 6,
    disponibles: 1,
    descripcion: {
      paginas: 180,
      editorial: "Editorial Sudamericana",
      fechaPublicacion: "1961",
      resumen: "La historia del coronel y su esposa, esperando la pensión que nunca llega.",
    },
  },
  {
    nombre: "Memorias de mis putas tristes",
    autor: "Gabriel García Márquez",
    genero: "Ficción erótica",
    tema: "Amor en la vejez",
    isbn: "978-84-89295-47-5",
    ejemplares: 10,
    disponibles: 4,
    descripcion: {
      paginas: 112,
      editorial: "Editorial Norma",
      fechaPublicacion: "2004",
      resumen: "La historia de un anciano periodista y su amor por una joven prostituta.",
    },
  },
  {
    nombre: "La casa de las dos palmas",
    autor: "Manuel Mejía Vallejo",
    genero: "Novela",
    tema: "Historia familiar",
    isbn: "978-958-30-0500-1",
    ejemplares: 8,
    disponibles: 5,
    descripcion: {
      paginas: 312,
      editorial: "Editorial Planeta",
      fechaPublicacion: "1988",
      resumen: "La vida de una familia antioqueña en el siglo XIX y su decadencia.",
    },
  },
  {
    nombre: "La marquesa de Yolombó",
    autor: "Tomás Carrasquilla",
    genero: "Histórica",
    tema: "Colonialismo",
    isbn: "978-958-30-0500-2",
    ejemplares: 10,
    disponibles: 6,
    descripcion: {
      paginas: 430,
      editorial: "Editorial Planeta",
      fechaPublicacion: "1926",
      resumen: "La historia de una mujer poderosa en la época colonial de Colombia.",
    },
  },
  {
    nombre: "Cóndores no entierran todos los días",
    autor: "Gustavo Álvarez Gardeazábal",
    genero: "Novela",
    tema: "Violencia política",
    isbn: "978-958-30-0500-3",
    ejemplares: 12,
    disponibles: 7,
    descripcion: {
      paginas: 289,
      editorial: "Editorial Planeta",
      fechaPublicacion: "1972",
      resumen: "La violencia partidista en Colombia durante los años 50.",
    },
  },
  {
    nombre: "La hojarasca",
    autor: "Gabriel García Márquez",
    genero: "Realismo mágico",
    tema: "Soledad",
    isbn: "978-84-204-6714-6",
    ejemplares: 9,
    disponibles: 3,
    descripcion: {
      paginas: 191,
      editorial: "Editorial Sudamericana",
      fechaPublicacion: "1955",
      resumen: "La historia de un pueblo en decadencia a través de tres generaciones.",
    },
  },
  {
    nombre: "Del amor y otros demonios",
    autor: "Gabriel García Márquez",
    genero: "Realismo mágico",
    tema: "Amor",
    isbn: "978-84-204-6714-7",
    ejemplares: 11,
    disponibles: 5,
    descripcion: {
      paginas: 208,
      editorial: "Editorial Sudamericana",
      fechaPublicacion: "1994",
      resumen: "La historia de una niña con supuestos poderes sobrenaturales en la Cartagena colonial.",
    },
  },
];

export default libros;
